# The name of the application to be built (binary will be this with a `.aplx`
# extension)
APP = lighthouse

# Directory to place compilation artefacts (must include trailing slash)
BUILD_DIR = ./build/

# The sources to be compiled
SOURCES = $(SOURCE_DIR)/examples/lighthouse/lighthouse.c

include ../../Makefile.common
