# Copyright (c) 2020 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# This workflow will install Python dependencies, run tests, lint and rat with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Actions
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout SupportScripts
      uses: actions/checkout@v3
      with:
        repository: SpiNNakerManchester/SupportScripts
        path: support
    - name: Install pip, etc
      uses: ./support/actions/python-tools
    - name: Install Spinnaker Dependencies
      uses: ./support/actions/checkout-spinn-deps
      with:
        repositories: >
          SpiNNUtils SpiNNMachine SpiNNMan PACMAN DataSpecification spalloc
          SpiNNFrontEndCommon SpiNNakerGraphFrontEnd TestBase
        install: true
    - name: Setup
      uses: ./support/actions/run-setup

#    # Add this when tests are built
    - name: Create a configuration file
      uses: ./support/actions/configure-spynnaker
      with:
        board-address: spinn-4.cs.man.ac.uk
    - run: mv ~/.spynnaker.cfg ~/.spiNNakerGraphFrontEnd.cfg

    - name: Test with pytest
      uses: ./support/actions/pytest
      with:
        tests: unittests
        coverage: ${{ matrix.python-version == 3.8 }}
        cover-packages: ${{ env.CODE_PATHS }}
        coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Lint with flake8
      run: flake8 mcmc mcmc_examples
    - name: Lint with pylint
      uses: ./support/actions/pylint
      with: 
        package: mcmc mcmc_examples
        exitcheck: 39

    - name: Run rat copyright enforcement
      if: matrix.python-version == 3.8
      uses: ./support/actions/check-copyrights

#    # Add the following as required in the future
#    - name: Validate XML
#      if: matrix.python-version == 3.8
#      uses: ./support/actions/validate-xml
#      with:
#        base-path: mcmc mcmc_examples

